team_names = [
    'Vancouver Canucks',
    'Edmonton Oilers',
    'Los Angeles Kings',
    'Vegas Golden Knights',
    'Calgary Flames',
    'Seattle Kraken',
    'Anaheim Ducks',
    'San Jose Sharks',
    'Colorado Avalanche',
    'Dallas Stars',
    'Winnipeg Jets',
    'Nashville Predators',
    'Minnesota Wild',
    'St. Louis Blues',
    'Arizona Coyotes',
    'Chicago Blackhawks',
    'Boston Bruins',
    'Florida Panthers',
    'Toronto Maple Leafs',
    'Tampa Bay Lightning',
    'Detroit Red Wings',
    'Buffalo Sabres',
    'Montreal Canadiens',
    'Ottawa Senators',
    'New York Rangers',
    'Carolina Hurricanes',
    'Philadelphia Flyers',
    'Washington Capitals',
    'New York Islanders',
    'New Jersey Devils',
    'Pittsburgh Penguins',
    'Columbus Blue Jackets'
]